name: run tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'signatures/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'signatures/**'

jobs:
  ci-service:
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      contents: read
    timeout-minutes: 4
    strategy:
      matrix:
        node-version: [18, 20]
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: |
          npm install
      - name: Run test suite
        run: npm run test

