name: run tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'signatures/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'signatures/**'

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

env:
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

jobs:
  ci-service:
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      contents: read
    timeout-minutes: 4
    strategy:
      matrix:
        node-version: [18, 20]
        os: [windows-latest]
    steps:
      - name: Install
        run: |
          npm install
      - name: Run test suite
        run: npm run test

